baseURL = 'http://example.org/'
title = "VincenzoFehring.com"
languageCode = 'en-us'
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "github-style"
preserveTaxonomyNames = true

[params]
    author = "Vincenzo Fehring"
    description = "A collection of random thoughts, change logs, notes, and postmortems related to my history as a software developer."
    avatar = "profile.JPG"
    github = "https://github.com/vfehring"
    rss = true
    lastmod = true
    favicon = "/images/github.png"
    location = "Houston, TX"
